def program():    

    print('░▒▓█ ░▒▓█▓▒░▒▓█▓▒░▒▓░▒▓█ ░▒▓█▓▒░▒▓█▓▒░▒▓░▒▓█ ░▒▓█▓▒░▒▓█▓▒░▒▓')
    print('░░▒ Welkom bij Cell Escape een text based adventure game. ▓█')
    print('░▒▓█ ░▒▓█▓▒░▒▓█▓▒░▒▓░▒▓█ ░▒▓█▓▒░▒▓█▓▒░▒▓░▒▓█ ░▒▓█▓▒░▒▓█▓▒░▒▓')
    print('░ Je zit opgesloten in een cell omdat je snoepjes hebt  ░▒▓█')
    print('░ gestolen bij de kruidvat. Je hebt hiervoor levenslang ░▒▓█')
    print('░ gekregen en bent het hier niet mee eens. Dus besluit  ░▒▓█')
    print('░ je te onstappen. Je zit in een oude cell die eigenlijk░▒▓█')
    print('░ vervangen moest worden, ontsnappen gaat dus wel lukken░▒▓█')
    print('░ of toch niet? De keuzes lichen in jou handen succes.  ░▒▓█')
    print('░▒▓█░▒▓█░▒▓█░▒▓█░▒▓█░▒▓█░▒▓█░▒▓█░▒▓█░▒▓█░▒▓█░▒▓█░▒▓█░▒▓█░▒▓█')
    print('')
    input('● Druk enter om te beginnen ')
    print('* Cell Escape is begonnen! ')
    print('* Je bevindt je in een cell, een oude cell. ')
    print('  Je doel is om te onstappen uit deze gevangenis')
    print('')
    print('* De bewaker komt net langs met de lunch')
    lunch = input('● Heb je honger? ja/nee ')
    if (lunch == 'ja'):
        print('* De pap is wel te eten alleen vind je al snel een mesje in het eten')
        print('● knife collected!')
        print('* Met het mesje kun je nu proberen het tralies door te snijden')
        snijden = input('● Wil je je mesje gebruiken? ja/nee ')

        if (snijden == 'ja'):
            print('zagen...')
            print('')
            print('zagen...')
            print('')
            print('zagen...')
            print('* het duurde even maar het is je gelukt om door het tralies te zagen!')
            print('* Nu moet je nog veilig buiten komen.')
            print('* Je ziet aan de eind van de gang een rampje met tralies ervoor ')
            keuze1 =input('Wil je het tralies doorzagen of doorlopen? doorzagen/doorlopen ')

            if (keuze1 == 'doorzagen'):
                print('zagen...')
                print('')
                print('zagen...')
                print('')
                print('zagen...')
                print('* Het ziet ernaar uit dat je op de 6e verdieping zit')
                print('* en dus niet uit het raam kan springen')
                print('* Je staat te lang bij het raam en een bewaker ziet je')
                keuze4 = input('Steek je hem dood? ja/nee ')
                if (keuze4 == 'ja'):
                    print('Je prikt de bewaker 1x maar dat is niet genoeg en de bewaker schiet jou dood.')
                    input('* Druk enter')
                    print('░██████╗░░█████╗░███╗░░░███╗███████╗  ░█████╗░██╗░░░██╗███████╗██████╗░')
                    print('██╔════╝░██╔══██╗████╗░████║██╔════╝  ██╔══██╗██║░░░██║██╔════╝██╔══██╗')
                    print('██║░░██╗░███████║██╔████╔██║█████╗░░  ██║░░██║╚██╗░██╔╝█████╗░░██████╔╝')
                    print('██║░░╚██╗██╔══██║██║╚██╔╝██║██╔══╝░░  ██║░░██║░╚████╔╝░██╔══╝░░██╔══██╗')
                    print('╚██████╔╝██║░░██║██║░╚═╝░██║███████╗  ╚█████╔╝░░╚██╔╝░░███████╗██║░░██║')
                    print('░╚═════╝░╚═╝░░╚═╝╚═╝░░░░░╚═╝╚══════╝  ░╚════╝░░░░╚═╝░░░╚══════╝╚═╝░░╚═╝')

                else:
                    input('* Ren je weg of geef je je over? rennen/overgeven ')
                    if(keuze6 == 'rennen'):
                        print('* de bewaker rent achter je aan')
                        print('  en schiet je meerde malen    ')
                        input('  Druk enter ')
                        print('Je overlijdt aan je verwondingen')
                        print('░██████╗░░█████╗░███╗░░░███╗███████╗  ░█████╗░██╗░░░██╗███████╗██████╗░')
                        print('██╔════╝░██╔══██╗████╗░████║██╔════╝  ██╔══██╗██║░░░██║██╔════╝██╔══██╗')
                        print('██║░░██╗░███████║██╔████╔██║█████╗░░  ██║░░██║╚██╗░██╔╝█████╗░░██████╔╝')
                        print('██║░░╚██╗██╔══██║██║╚██╔╝██║██╔══╝░░  ██║░░██║░╚████╔╝░██╔══╝░░██╔══██╗')
                        print('╚██████╔╝██║░░██║██║░╚═╝░██║███████╗  ╚█████╔╝░░╚██╔╝░░███████╗██║░░██║')
                        print('░╚═════╝░╚═╝░░╚═╝╚═╝░░░░░╚═╝╚══════╝  ░╚════╝░░░░╚═╝░░░╚══════╝╚═╝░░╚═╝')

                    else:
                        print('Wie geeft zich nou weer over? noob')
                        input('Druk enter ')
                        print('░██████╗░░█████╗░███╗░░░███╗███████╗  ░█████╗░██╗░░░██╗███████╗██████╗░')
                        print('██╔════╝░██╔══██╗████╗░████║██╔════╝  ██╔══██╗██║░░░██║██╔════╝██╔══██╗')
                        print('██║░░██╗░███████║██╔████╔██║█████╗░░  ██║░░██║╚██╗░██╔╝█████╗░░██████╔╝')
                        print('██║░░╚██╗██╔══██║██║╚██╔╝██║██╔══╝░░  ██║░░██║░╚████╔╝░██╔══╝░░██╔══██╗')
                        print('╚██████╔╝██║░░██║██║░╚═╝░██║███████╗  ╚█████╔╝░░╚██╔╝░░███████╗██║░░██║')
                        print('░╚═════╝░╚═╝░░╚═╝╚═╝░░░░░╚═╝╚══════╝  ░╚════╝░░░░╚═╝░░░╚══════╝╚═╝░░╚═╝')
            else:
                print('* Je loopt door de gang en vindt uiteindelijk een trappenhuis')
                keuze3 = input('ga je omhoog of omlaag in het trappenhuis? ')
                if(keuze3 == 'omlaag'):
                    print('* Je komt aan op de beganegrond en ziet een nooduitgang')
                    input('  Doe de deur open met Enter ')
                    print('  De deur gaat open en je rent je vrijheid tegmoet')
                    print('██╗░░░██╗██╗░█████╗░████████╗░█████╗░██████╗░██╗░░░██╗  ██████╗░░█████╗░██╗░░░██╗░█████╗░██╗░░░░░███████╗')
                    print('██║░░░██║██║██╔══██╗╚══██╔══╝██╔══██╗██╔══██╗╚██╗░██╔╝  ██╔══██╗██╔══██╗╚██╗░██╔╝██╔══██╗██║░░░░░██╔════╝')
                    print('╚██╗░██╔╝██║██║░░╚═╝░░░██║░░░██║░░██║██████╔╝░╚████╔╝░  ██████╔╝██║░░██║░╚████╔╝░███████║██║░░░░░█████╗░░')
                    print('░╚████╔╝░██║██║░░██╗░░░██║░░░██║░░██║██╔══██╗░░╚██╔╝░░  ██╔══██╗██║░░██║░░╚██╔╝░░██╔══██║██║░░░░░██╔══╝░░')
                    print('░░╚██╔╝░░██║╚█████╔╝░░░██║░░░╚█████╔╝██║░░██║░░░██║░░░  ██║░░██║╚█████╔╝░░░██║░░░██║░░██║███████╗███████╗')
                    print('░░░╚═╝░░░╚═╝░╚════╝░░░░╚═╝░░░░╚════╝░╚═╝░░╚═╝░░░╚═╝░░░  ╚═╝░░╚═╝░╚════╝░░░░╚═╝░░░╚═╝░░╚═╝╚══════╝╚══════╝')
                else:
                    print('* De bewaking spot je boven en er is geen weg uit')
                    input('Druk enter ')
                    print('░██████╗░░█████╗░███╗░░░███╗███████╗  ░█████╗░██╗░░░██╗███████╗██████╗░')
                    print('██╔════╝░██╔══██╗████╗░████║██╔════╝  ██╔══██╗██║░░░██║██╔════╝██╔══██╗')
                    print('██║░░██╗░███████║██╔████╔██║█████╗░░  ██║░░██║╚██╗░██╔╝█████╗░░██████╔╝')
                    print('██║░░╚██╗██╔══██║██║╚██╔╝██║██╔══╝░░  ██║░░██║░╚████╔╝░██╔══╝░░██╔══██╗')
                    print('╚██████╔╝██║░░██║██║░╚═╝░██║███████╗  ╚█████╔╝░░╚██╔╝░░███████╗██║░░██║')
                    print('░╚═════╝░╚═╝░░╚═╝╚═╝░░░░░╚═╝╚══════╝  ░╚════╝░░░░╚═╝░░░╚══════╝╚═╝░░╚═╝')

    else:
        print('* Je bent moe en gaat even slapen')
        print('  Je wordt weer wakker en het is alweer avond')
        print('  De bewaker komt weer langs en deze keer met het het avondeten')
        print('  Deze keer staat soep op het menu')
        input('● Typ eet om je soep te eten ')
        print('* Je soep was lekker')
        print('  Je komt op het idee om de soeplepel te bewaren')
        print('● Soeplepel collected')
        print('* Je kunt met de soeplepel een gat graven in je cell om daardoor te onstappen')
        keuze9 = input('Wil je gaan graven? ja/nee ')
        if keuze9 == 'ja':   

            print('graven...')
            print('')
            print('graven...')
            print('')
            print('graven...')
            print('')
            print('* Het is gelukt om een gat te graven')
            print('  je bent nu buiten')
            print('* Je moet alleen nog over of onder het hek heen')
            keuze2 = input('  Hoe ga je het hek over? onder/boven ')
            if (keuze2 == 'onder'):
                print('* je bent hebt je lepel nog bij je')
                keuze8 = input('Wil je gaan graven? ja/nee ')
                if keuze8 == 'ja':
                    print('graven...')
                    print('')
                    print('graven...')
                    print('')
                    print('graven...')
                    input('● Druk enter')
                    print('* Het is je gelukt te ontsnappen!')
                    print('██╗░░░██╗██╗░█████╗░████████╗░█████╗░██████╗░██╗░░░██╗  ██████╗░░█████╗░██╗░░░██╗░█████╗░██╗░░░░░███████╗')
                    print('██║░░░██║██║██╔══██╗╚══██╔══╝██╔══██╗██╔══██╗╚██╗░██╔╝  ██╔══██╗██╔══██╗╚██╗░██╔╝██╔══██╗██║░░░░░██╔════╝')
                    print('╚██╗░██╔╝██║██║░░╚═╝░░░██║░░░██║░░██║██████╔╝░╚████╔╝░  ██████╔╝██║░░██║░╚████╔╝░███████║██║░░░░░█████╗░░')
                    print('░╚████╔╝░██║██║░░██╗░░░██║░░░██║░░██║██╔══██╗░░╚██╔╝░░  ██╔══██╗██║░░██║░░╚██╔╝░░██╔══██║██║░░░░░██╔══╝░░')
                    print('░░╚██╔╝░░██║╚█████╔╝░░░██║░░░╚█████╔╝██║░░██║░░░██║░░░  ██║░░██║╚█████╔╝░░░██║░░░██║░░██║███████╗███████╗')
                    print('░░░╚═╝░░░╚═╝░╚════╝░░░░╚═╝░░░░╚════╝░╚═╝░░╚═╝░░░╚═╝░░░  ╚═╝░░╚═╝░╚════╝░░░░╚═╝░░░╚═╝░░╚═╝╚══════╝╚══════╝')
                else: 
                    print('De bewaking heeft je gespot')
                    print('Er wordt meerder malen op je geschoten ')
                    input('Druk enter')
                    print('Je bent gestoveren aan je wonden')
                    print('░██████╗░░█████╗░███╗░░░███╗███████╗  ░█████╗░██╗░░░██╗███████╗██████╗░')
                    print('██╔════╝░██╔══██╗████╗░████║██╔════╝  ██╔══██╗██║░░░██║██╔════╝██╔══██╗')
                    print('██║░░██╗░███████║██╔████╔██║█████╗░░  ██║░░██║╚██╗░██╔╝█████╗░░██████╔╝')
                    print('██║░░╚██╗██╔══██║██║╚██╔╝██║██╔══╝░░  ██║░░██║░╚████╔╝░██╔══╝░░██╔══██╗')
                    print('╚██████╔╝██║░░██║██║░╚═╝░██║███████╗  ╚█████╔╝░░╚██╔╝░░███████╗██║░░██║')
                    print('░╚═════╝░╚═╝░░╚═╝╚═╝░░░░░╚═╝╚══════╝  ░╚════╝░░░░╚═╝░░░╚══════╝╚═╝░░╚═╝')

            else:
                print('* Je klimt over het hek heen maar je haalt je open aan het prikkeldraad')
                keuze7 =input('  Wil je je t-shirt gebruiken om de verwondingen te verminderen? ja/nee ')
                if (keuze7 == 'ja'): 
                    print('Je gaat alsnogn dood aan je verwondingen')
                    input('Druk enter ')
                    print('je blood dood aan je verwondingen')
                    print('░██████╗░░█████╗░███╗░░░███╗███████╗  ░█████╗░██╗░░░██╗███████╗██████╗░')
                    print('██╔════╝░██╔══██╗████╗░████║██╔════╝  ██╔══██╗██║░░░██║██╔════╝██╔══██╗')
                    print('██║░░██╗░███████║██╔████╔██║█████╗░░  ██║░░██║╚██╗░██╔╝█████╗░░██████╔╝')
                    print('██║░░╚██╗██╔══██║██║╚██╔╝██║██╔══╝░░  ██║░░██║░╚████╔╝░██╔══╝░░██╔══██╗')
                    print('╚██████╔╝██║░░██║██║░╚═╝░██║███████╗  ╚█████╔╝░░╚██╔╝░░███████╗██║░░██║')
                    print('░╚═════╝░╚═╝░░╚═╝╚═╝░░░░░╚═╝╚══════╝  ░╚════╝░░░░╚═╝░░░╚══════╝╚═╝░░╚═╝')
                else:
                    input('Druk enter ')
                    print('je blood dood aan je verwondingen')
                    print('░██████╗░░█████╗░███╗░░░███╗███████╗  ░█████╗░██╗░░░██╗███████╗██████╗░')
                    print('██╔════╝░██╔══██╗████╗░████║██╔════╝  ██╔══██╗██║░░░██║██╔════╝██╔══██╗')
                    print('██║░░██╗░███████║██╔████╔██║█████╗░░  ██║░░██║╚██╗░██╔╝█████╗░░██████╔╝')
                    print('██║░░╚██╗██╔══██║██║╚██╔╝██║██╔══╝░░  ██║░░██║░╚████╔╝░██╔══╝░░██╔══██╗')
                    print('╚██████╔╝██║░░██║██║░╚═╝░██║███████╗  ╚█████╔╝░░╚██╔╝░░███████╗██║░░██║')
                    print('░╚═════╝░╚═╝░░╚═╝╚═╝░░░░░╚═╝╚══════╝  ░╚════╝░░░░╚═╝░░░╚══════╝╚═╝░░╚═╝')
        else:
            print('Er zit een nummer hangslot aan je cell')
            print('Je probeert de code kraken')
            print('Er loopt een bewaker langs en je ziet dat hij de code heeft')
            print('Je zag alleen het 1e cijfertje en je weet niet of het nou 4 of 9 was ')
            code1 =input("Welk cijfer denk je? ")
            if code1 != '4': 
                print('Goed geraden je hebt het eerste cijfer goed geraden')
                print('je moet nog een paar andere cijfers raden')
                code2 =input('Kies nummer 2: ')
                if code2 > '5':
                    code3 =input("Raad nummer 3: ")
                    if code3 < input('Raad nummer 4: ' ):
                        code4 =input('Raad nummer 5: ')
                        if code4 <= '3' ('Raad nummer 6: '):
                            if code5 >= '9':
                                print('██╗░░░██╗██╗░█████╗░████████╗░█████╗░██████╗░██╗░░░██╗  ██████╗░░█████╗░██╗░░░██╗░█████╗░██╗░░░░░███████╗')
                                print('██║░░░██║██║██╔══██╗╚══██╔══╝██╔══██╗██╔══██╗╚██╗░██╔╝  ██╔══██╗██╔══██╗╚██╗░██╔╝██╔══██╗██║░░░░░██╔════╝')
                                print('╚██╗░██╔╝██║██║░░╚═╝░░░██║░░░██║░░██║██████╔╝░╚████╔╝░  ██████╔╝██║░░██║░╚████╔╝░███████║██║░░░░░█████╗░░')
                                print('░╚████╔╝░██║██║░░██╗░░░██║░░░██║░░██║██╔══██╗░░╚██╔╝░░  ██╔══██╗██║░░██║░░╚██╔╝░░██╔══██║██║░░░░░██╔══╝░░')
                                print('░░╚██╔╝░░██║╚█████╔╝░░░██║░░░╚█████╔╝██║░░██║░░░██║░░░  ██║░░██║╚█████╔╝░░░██║░░░██║░░██║███████╗███████╗')
                                print('░░░╚═╝░░░╚═╝░╚════╝░░░░╚═╝░░░░╚════╝░╚═╝░░╚═╝░░░╚═╝░░░  ╚═╝░░╚═╝░╚════╝░░░░╚═╝░░░╚═╝░░╚═╝╚══════╝╚══════╝')

                else: 
                    print('░██████╗░░█████╗░███╗░░░███╗███████╗  ░█████╗░██╗░░░██╗███████╗██████╗░')
                    print('██╔════╝░██╔══██╗████╗░████║██╔════╝  ██╔══██╗██║░░░██║██╔════╝██╔══██╗')
                    print('██║░░██╗░███████║██╔████╔██║█████╗░░  ██║░░██║╚██╗░██╔╝█████╗░░██████╔╝')
                    print('██║░░╚██╗██╔══██║██║╚██╔╝██║██╔══╝░░  ██║░░██║░╚████╔╝░██╔══╝░░██╔══██╗')
                    print('╚██████╔╝██║░░██║██║░╚═╝░██║███████╗  ╚█████╔╝░░╚██╔╝░░███████╗██║░░██║')
                    print('░╚═════╝░╚═╝░░╚═╝╚═╝░░░░░╚═╝╚══════╝  ░╚════╝░░░░╚═╝░░░╚══════╝╚═╝░░╚═╝')                                                

            else: 
                print('░██████╗░░█████╗░███╗░░░███╗███████╗  ░█████╗░██╗░░░██╗███████╗██████╗░')
                print('██╔════╝░██╔══██╗████╗░████║██╔════╝  ██╔══██╗██║░░░██║██╔════╝██╔══██╗')
                print('██║░░██╗░███████║██╔████╔██║█████╗░░  ██║░░██║╚██╗░██╔╝█████╗░░██████╔╝')
                print('██║░░╚██╗██╔══██║██║╚██╔╝██║██╔══╝░░  ██║░░██║░╚████╔╝░██╔══╝░░██╔══██╗')
                print('╚██████╔╝██║░░██║██║░╚═╝░██║███████╗  ╚█████╔╝░░╚██╔╝░░███████╗██║░░██║')
                print('░╚═════╝░╚═╝░░╚═╝╚═╝░░░░░╚═╝╚══════╝  ░╚════╝░░░░╚═╝░░░╚══════╝╚═╝░░╚═╝')
program()